### ISSUE TITLE
ID generation strategy

### ISSUE THREAD

**Issue by mkopacz** [clientIO/joint#1032]
Hi,

is there any way to instruct JointJS on how to generate IDs for new cells? I need IDs not to start with a digit, which is not always the case when using UUIDs as IDs.

Thanks

**Comment by mkopacz** [comment]
Thank you for your response.

Unfortunately, I do not create new elements on my own. I implemented a copy-paste functionality in which I used: `dia.Graph.prototype.cloneSubgraph` to copy the elements of my diagram. This function uses `dia.Element.prototype.clone` internally.

The best solution for now, that I could come up with is sth like this:

```
const originalUuid = overrideUuid();
const clonedSubgraph = process.asGraph().cloneSubgraph([cell], { deep: true });
restoreUuid(originalUuid);

function overrideUuid(): () => string {
  const originalUuid = joint.util.uuid;
  joint.util.uuid = () => `copy_${originalUuid()}`;
  return originalUuid;
}

function restoreUuid(originalUuid: () => string) {
  joint.util.uuid = originalUuid;
}
```

**Comment by kumilingus** [comment]
Hi Mariusz,

I see.  The `cloneCells` method is not that easy to adjust. I think we should create a new `dia.Cell` method e.g. `generateId() => joint.util.uuid()` and use this instead of calling `joint.util.uuid()` directly at multiple places. Then, you will be able to override a single cell method to change the ID generation strategy.
