### ISSUE TITLE
Linking one link to another

### ISSUE THREAD

**Issue by savolkov** [clientIO/joint#1053]
Hi there!

Is there a posibility to link one link to another? I found this [question](https://stackoverflow.com/questions/20290882/linking-one-link-to-another-in-jointjs) but there is no answer. Anything changed from that times?

We need to create a link given on the screenshot. ![Check dash and dash line](https://user-images.githubusercontent.com/18547316/51981087-c4bd5880-24b3-11e9-84c4-7788fda02dea.png)

Thanks.

**Comment by kumilingus** [comment]
This is not supported yet. We're working on this though and hopefully this will be ready for the next big release.
Right now, you would need to create a tiny element between `masterClass2` and `LookUpClass2`, which would be connected to the `masterClass` too.

**Comment by kumilingus** [comment]
It's now possible in `v3.0.0`.

```javascript
// for instance
link1.target(link2, { anchor: { name: 'connectionPerpendicular' }});
```

**Comment by kafnevod** [comment]
Hi there!
In order to implement the link-to-link connection mechanism in our project, we are moving from version 2. to version 3.0.2 and faced with a problem.
We use in the Ember  environment
During initialization:
```
_(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('backbone'), require('lodash'), require('jquery')) :
    typeof define === 'function' && define.amd ? define(['exports', 'backbone', 'lodash', 'jquery'], factory) :
    (global = global || self, factory(global.joint = {}, global.Backbone, global._, global.$));
}(this, function (exports, Backbone, _, $) { 'use strict';_
```
...
factory is called as 

`factory(exports, require('backbone'), require('lodash'), require('jquery')`

not as
`(global = global || self, factory(global.joint = {}, global.Backbone, global._, global.$))`

In this case global variable joint remain unitialized and not linked with exports variable
and not initialized in lines 28156-28157:
```
exports.layout = layout$1;
exports.format = format$1;
exports.version = version;
exports.shapes = index$4;
...
```

In method define() of Cell object (lines 11437-11449) 
```
           if (typeof joint !== 'undefined' && has(joint, 'shapes')) {
                setByPath(joint.shapes, type, Cell, '.');
            }
```
method` setByPath() `is not called 
and  `define() `method in our Ember-project
`joint.shapes.basic.Generic.define(...)`
works incorrectly

I resolve this problem by adding operator
`var joint = exports;`
if factory method of jointjs:
```
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('backbone'), require('lodash'), require('jquery')) :
    typeof define === 'function' && define.amd ? define(['exports', 'backbone', 'lodash', 'jquery'], factory) :
    (global = global || self, factory(global./*joint*/ = {}, global.Backbone, global._, global.$));
}(this, function (exports, Backbone, _, $) { 'use strict';
    **var joint = exports;**
    Backbone = Backbone && Backbone.hasOwnProperty('default') ? Backbone['default'] : Backbone;
```
**But not sure that this is the right decision.

What do you recommend in this case?**

**Comment by kumilingus** [comment]
Hi, 

> joint.shapes.basic.Generic.define(...) works incorrectly

Could you elaborate more on this one? Isn't it related to this issue https://github.com/clientIO/joint/issues/1133 by any change? Could you try pass the cell and cellView namespaces as mentioned in the other issue?
