### ISSUE TITLE
Uncaught ReferenceError: dagre is not defined

### ISSUE THREAD

**Issue by lciolecki** [clientIO/joint#1129]
Hi again! :)

After update jointjs to version 3 I have problem with dagre.. Problem is on toGraphLib function at line `var glGraph = new dagre.graphlib.Graph(glGraphType);`.

I use standard webpack configuration with react app. 

Any idea how solve this?

**Comment by vtalas** [comment]
Hi, it's fixed in the #1122. In the previous version, there was the `dagre` included explicitly in the DirectedGraph sources. We encounter an issue with this during the "esm modularization" as the `dagre` was included even if the app is not using DirectedGraph at all. To prevent that, you need to inject the `dagre` (or just the `graphlib`) into the DirectedGraph as an option  - see the mentined PR for details

**Comment by vtalas** [comment]
```

**Comment by lciolecki** [comment]
Okey, but for now this doesn't work? So when you will release new verison with fix?  :)

**Comment by vtalas** [comment]
as a workaround you can include dagre and graphlib separately:

```
<script src="../../node_modules/graphlib/dist/graphlib.core.js"></script>
<script src="../../node_modules/dagre/dist/dagre.core.js"></script>
```

**Comment by lciolecki** [comment]
Okey, on webpack app workaround should look likes:
`
import * as dagre from 'dagre'
window.dagre = dagre
`
It works.
