### ISSUE TITLE
Serialization error: markup required

### ISSUE THREAD

**Issue by WhiteMaple13** [clientIO/joint#1133]
I am encountering an unexpected error while using JointJS in an Angular application. After I create graph, paper and a rectangle like in the following: 

 ```
private graph: joint.dia.Graph;
 private paper: joint.dia.Paper;

  ngOnInit() {
    this.graph = new joint.dia.Graph();
    this.paper = new joint.dia.Paper({
      el: this.paperElement.nativeElement,
      width: 1001,
      height: 801,
      model: this.graph,
      gridSize: 20,
      drawGrid: { name: "mesh" }
    });
    let rect = new joint.shapes.standard.Rectangle();
    rect.position(50, 20);
    rect.resize(100, 40);
    rect.attr({
      body: {
        fill: "blue"
      },
      label: {
        text: "abc",
        fill: "white"
      }
    });
    rect.addTo(this.graph);
```
I am trying to serialize the graph to JSON and load it again, like so
```
    let data = this.graph.toJSON();
    console.log(JSON.stringify(data));
    this.graph.fromJSON(data);
```
But when i try to run the application, i get the following error:

> Error: dia.ElementView: markup required

The serialized json looks like the following:
`{"cells":[{"type":"standard.Rectangle","position":{"x":50,"y":20},"size":{"width":100,"height":40},"angle":0,"id":"64a15c16-2145-4fcb-b838-5271d69d4fa7","z":1,"attrs":{"body":{"fill":"blue"},"label":{"fill":"white","text":"abc"}}}]}`

Am i doing something wrong or is this a bug?

**Comment by jmn69** [comment]
Hi, 

Same for me with a React application.

So far, i am able to make it work by setting the markup manually for each element. 
I debugged the joint.js lib and if the markup is not specified we have this error.
But this is not logical for standard shapes we shouldn't have to specified markup.

I think we are missing something but what ?

**Comment by kumilingus** [comment]
If there is no global `joint` variable, you need to pass the shapes namespace explicitly to `graph` (for models) and `paper` (for views).
```js
const namespace = joint.shapes; // e.g. { standard: { Rectangle: RectangleElementClass }}
const graph = new joint.dia.Graph({ /* attributes of the graph */ }, { cellNamespace: namespace });
const paper = new joint.dia.Paper({ cellViewNamespace: namespace });
```

**Comment by vtalas** [comment]
discussed here as well https://github.com/clientIO/joint/issues/1130#issuecomment-507993015

**Comment by thomaspeugeot** [comment]
> If there is no global `joint` variable, you need to pass the shapes namespace explicitly to `graph` (for models) and `paper` (for views).

Great. However, could you provide a more detailled explanation ? This is a problem I met with very simple elements. 

Why is it necessary to have this declaration ? 

Why is 
```ts
, { cellNamespace: namespace }
```
 provided in the second part of the constructor ?

**Comment by kumilingus** [comment]
Hi @thomaspeugeot, I am glad you asked.
The issue manifests when you try to deserialize a JSON and create an actual JointJS element model.

---
```js
graph.addCell({ type: 'standard.Rectangle', size: { width: 100, height: 100 }})
```
Here, we need to find the actual constructor for `standard.Rectangle`.

---
```js
new joint.shapes['standard']['Rectangle']({ size: { width: 100, height: 100 }});
```
It's easy as this, if there is a global `joint` variable defined.

---
```js
graph.get('cells').cellNamespace['standard']['Rectangle'](({ size: { width: 100, height: 100 }});
```
Otherwise (when JointJS is loaded as module), we need to use the shapes namespace defined on the graph collection.

---
```js
const graph = new joint.dia.Graph({ /* attributes */ }, { cellNamespace: joint.shapes });
```
The `cellNamespace` property is set [here](https://github.com/clientIO/joint/blob/master/src/dia/Graph.mjs#L15-L21) in the graph constructor.
It can't be the first parameter because the graph is a `Backbone.Model`. i.e. the constructor accepts attributes as the first parameter, which could be serialized later. The `cellNamespace` can not be serialized.
```js
const graph = new joint.dia.Graph({ test: true });
graph.toJSON(); // { test: true, cells: [] }
```
The second parameter is the constructor options. At the time of the model initialization we store the given namespace. If it is not passed, we set NO default cell namespace.

---
We don't want to import the actual `joint.shapes` and use it [here](https://github.com/clientIO/joint/blob/master/src/dia/Graph.mjs#L19) for the default value.
```js
import * from 'src/shapes/index.mjs'.
```
Going forward, it would prevent you from cherry-picking shapes you want to use in your application and NOT load/import any other shapes (If you are using `src` files in your app now, you can bundle just core JointJs and shapes, that will be actually used in your app).

---
We could have also changed the API of some of the methods to require a `cellNamespace`.
```js
graph.fromJSON(json, cellNamespace);
graph.addCell(cellJSON, cellNamespace);
```
We've chosen the other option though.

---
If there was a better way how to go around this, I'd love to know about it. Thank you!

**Comment by thomaspeugeot** [comment]
Hi @kumilingus  & thks for this  answer.

Your answer is detailled and clear. I now understand the rationale for the extra attribute: a need to inform the derialiazer of what shape constructor it is supposed to call (I will comment the code with this).

I also understand that this API design opens the freedom to call other shape constructors than the standard jointjs. I do not know how to go around this but IMHO, I would keep the standard API simple and make the extra freedom for a more complex API. This is a very humble opinion since I am no expert in js things

Best regards

Thomas

**Comment by kumilingus** [comment]
@thomaspeugeot , this would, unfortunately, result in importing all JointJS shapes (UML, ORG, PN, ..) even if you are not about to use them (even if you don't call `FromJSONWithJointShapesNamespace()` at all).
Perhaps [dynamic imports](https://v8.dev/features/dynamic-import) would be an answer to this.

**Comment by thomaspeugeot** [comment]
@kumilingus , sorry, but what would be the problem with importing all JointJS shapes ?

**Comment by kumilingus** [comment]
@thomaspeugeot , the size of the resulting bundle.
```js
// This would import all JointJS shapes.
// And there would be no way to import the graph only.
import * from 'src/dia/graph.mjs';
```
