### ISSUE TITLE
basic_mjs.Circle is undefined when loading joint.shapes.fsa in 3.0.4

### ISSUE THREAD

**Issue by amg0** [clientIO/joint#1170]
Circle does not appear as a member of basic_mjs on line 13.
this is a simple setup , loaded scripts are joint.js and joint.shapes.fsa.js
<img width="615" alt="stack" src="https://user-images.githubusercontent.com/16444411/64021914-4a31e580-cb35-11e9-8301-77731ce5028e.PNG">

**Comment by vtalas** [comment]
@amg0 this is a bug in the ES5 build, indeed, Meanwhile you can use a quick workaround for that. On the last line of the file, there should be `joint.shapes.basis` injected instead of the `joint.shapes`. So it should look like this: 

`...}(this.joint.shapes.fsa = this.joint.shapes.fsa || {}, joint.shapes.basic, joint.dia, joint.dia));`

**Comment by vtalas** [comment]
fixed by #1174

**Comment by kumilingus** [comment]
Fixed in `v3.1`.
