### ISSUE TITLE
Join API causes memory leak in React SPA

### ISSUE THREAD

**Issue by ruslan-shuster** [clientIO/joint#1239]
We have a single-page react application using rappid and joint libraries. The components that use rappid functionality are not being garbage-collected. When I investigated memory snapshots I see that the object roots are in SVG-prefixed 'window' properties. What can I do to prevent such behaviour? We use rappid version 2.4.0(joint 2.2.1).
<img width="942" alt="Screen Shot 2020-01-04 at 14 23 09" src="https://user-images.githubusercontent.com/58134692/71813772-38cc8d00-3083-11ea-9ec4-0962de394752.png">

**Comment by kumilingus** [comment]
It is necessary to call `remove()` method on every `mvc.View` in order to dispose it properly.

**Comment by LouisSung** [comment]
Sorry for asking question here rather than new an issue. (I'll do so if necessary)
Actually, I am facing similar memory leaks issue recently.

I'm using Angular 8 rather than the React. (and JointJS 3.1.1)
In my case, I do add `paper.remove()` and print logs in `ngOnDestory()`, which means those paper should have called remove() correctly when route to other pages.
However, there are still thousand of leaks here and I don't know how to fix it... (I even call graph.clear() at the same time but still don't work)

![image](https://user-images.githubusercontent.com/37973545/72675490-f746d380-3abf-11ea-98ea-723bf5e008cc.png)
