### ISSUE TITLE
Events for insertView/removeView

### ISSUE THREAD

**Issue by luis-carlos-campos** [clientIO/joint#1301]
Hello everyone,

I have a "virtual paper" (async + viewport)...
Whenever a cell is inserted/removed I'd like to perform some adjustments. (So I've created my own event)
What are your thoughts on having a default paper event for those operations? Does it sound reasonable or too specific?

Thanks!

**Comment by kumilingus** [comment]
Hi @luis-carlos-campos, by `inserted`/`removed` you mean mount/unmount (as a result of the `viewport` function) or when a cell view is added/removed because the model was added to/removed from the graph?
What are these adjustments you were doing? Let me please understand the use-case better. Thank you.

**Comment by luis-carlos-campos** [comment]
Hi @kumilingus

I appreciate your time.

I meant mount/unmount as a result of the viewport fn...
"A new view is going to be added to the DOM."

In a nutshell, I've to perform a few SVG manipulation...
Like:
 - Change x/y of a node due to a non visible node. (that could become visible)
 - Change y due to a visible element with dynamic height (stacking <text/>)

**Comment by kumilingus** [comment]
Perhaps you could create a custom element view and add an additional `initFlag` and run whatever you need when the elementView is rendered for the first time inside the `confirmUpdate` method.

Example: https://github.com/clientIO/joint/blob/master/src/shapes/pn.mjs#L52-L62

```js
joint.dia.ElementView.extend({

    initFlag: joint.dia.ElementView.prototype.initFlag.concat(['STACK']),

    confirmUpdate: function(...args) {
        let flags = joint.dia.ElementView.prototype.confirmUpdate.call(this, ...args);
        if (this.hasFlag(flags, 'STACK')) {
            // Run whatever you need here
            flags = this.removeFlag(flags, 'STACK');
        }
        return flags;
    }
}
```

I still completely do not understand what manipulations you need to perform when the view is mounted. Is it because there were some changes to the model while the view was unmounted from the DOM?

Then, it needs to be done like this (when the `tokens` model attribute changes, the paer will run the view `confirmUpdate` method when the view mounted back to the DOM).
https://github.com/clientIO/joint/blob/master/src/shapes/pn.mjs#L48-L50

Feel free to drop me an email with some source code at roman@client.io. Thanks you.

**Comment by luis-carlos-campos** [comment]
It makes total sense. I appreciate your time for clarifying this.
Thank you Roman. I'll close this request.
