### ISSUE TITLE
Rappid visio import Link vertices

### ISSUE THREAD

**Issue by Bloeffy** [clientIO/joint#1467]
Hi, i am using the Testversion of rappid and cant find a possibility to get the vertices of an link that got imported from a visio sheet. Element coordinates are easy to find, but for link/connects i wasnt able to find a way. Is there a way to get them?

**Comment by msmiechowski** [comment]
Hi @Bloeffy . Visio doesn't use a separate concept for vertices of a Connect shape. Instead it uses same Section that's used for drawing any other Shape - `Geometry`. 

What you can do is get the Geometries the Visio shape has defined, decide which Geometry Section is the one containing data about line vertices, and then map that to the format you're interested in.

You can do it like so:
```javascript
       const cells = pageContent.toGraphCells({
            importConnect: (vsdConnect, sourceElement, targetElement) => {
                const vsdShape = vsdConnect.getShape();

                // get all geometry sections the shape contains
                const geometries = vsdShape.getGeometry();

                // pick the geometry section that contains data for the visible connection
                // this may vary depending on the shape used as Connect, so you'll have to evaluate which one is correct
                const geometry = geometries[0];

                // then you can get all the coordinate Visio Cells from that Section
                const vertexCells = geometry.getRows().map(row => {
                    return { x: row.getCell('x'), y: row.getCell('y') };
                });

                // or you can evaluate these Visio Cells to pixels
                const vertices = geometry.getRows().map(row => {
                    return { x: row.getCell('x')?.eval(), y: row.getCell('y')?.eval() };
                });
                
                // ... do your further logic
            }
        });
```

**Comment by Bloeffy** [comment]
Thanks for the fast answer, it will help me a lot.

**Comment by msmiechowski** [comment]
@Bloeffy I'd need a bit more info to help you any further. I can only made a guess what the potential culprits are:

1. **The scientific notation result** - that's due to floating point operations. I suggest making an arbitrary decision to round it up.
2. **Number of vertices** - I'll fix my previous comment as it is misleading. The result you're getting from Geometry section are coordinates and instructions rather than simple vertices. That means the first one is most probably a `MoveTo` or a `RelMoveTo`. Look up the Row data for each of those to learn what is the actual `instruction` (you'll be looking for the `type` property). You can refer to Visio documentation to learn a bit more about the particular rows: https://docs.microsoft.com/en-us/office/client-developer/visio/rows-visio-shapesheet-reference
3. **Mismatch in values** - this is most probably caused by unit type miscalculation. Could you provide a bit more info about the Connect itself, what's the used unit type and values in Visio. You can find that in the Connect Shape Sheet in Visio). Another thing would be the drawing scale which you can find in Page Setup (right click the page in Visio).

Looking at those numbers though, it does look a bit off. Maybe there's multiple Geometry sections on that shape?
A screenshot of the Connect Shape Sheet showing the Geometry section would be helpful to track down what's going on.

**Comment by Bloeffy** [comment]
Thanks for the answer, i wasnt able to find multible Geometry Sections on the Visio Shape Sheet. 
![image](https://user-images.githubusercontent.com/19932404/117654417-04487400-b196-11eb-81e7-e98f3b6a4155.png)

But i was able to place some vertices that are close to the ones on the visio sheet. 
```
const vertices = geometry.getRows().map(row => {
      return { x: row.getCell('x')?.eval(), y: row.getCell('y')?.eval() };
});

// array for the link vertices
let coordArray = [];
vertices.forEach(element => {
      // string to proof if the coordinate got an scientific notation
      let xString = '' + element.x;
      let yString = '' + element.y;
      if(element.x !== undefined && element.y !== undefined && !xString.includes('e') && !yString.includes('e')){
            // calculate the vertex x coordinate with the coordinate of the source and target
            let coords = {
                  x: element.x + sourceCoordinates.x,
                  y: element.y + targetCoordinates.y
            };
            coordArray.push(coords);
      }
});
```
I want to get the coordinates, without creating a new Link. It feels a bit like hacking but i think it will possibly work, because the vertices i create with this code are realy close to the original ones.

**Comment by msmiechowski** [comment]
I can see your Visio project uses metric system and `meters` for coordinates, this might pose an issue in current version.
You can solve it by:
1. Change Visio project settings to use inches
2. Don't use `eval()` and instead convert raw value to pixels by yourself. `1 meter` would be `3779.5275590551 pixels` if we are to trust https://www.unitconverters.net/typography/millimeter-to-pixel-x.htm

**Comment by Bloeffy** [comment]
Ok, i will try one of your solutions.

**Comment by msmiechowski** [comment]
As a side note, I don't think you need to check for the `e` sign. There's a number of things you could do to get the actual value here, but I don't think ignoring these is what you'd normally do. These are either close to zero or very large numbers, that both for some reason should be evaluated.

You can even use `Math.round(element.x)` if precision is not needed or even `Number.parseFloat(Number(element.x).toFixed(2))` if you want to fine tune the decimal places (that's for small numbers only though).

**Comment by Bloeffy** [comment]
i will try it thanks
