### ISSUE TITLE
parameter 'text' of function breakText

### ISSUE THREAD

**Issue by josenberg** [clientIO/joint#169]
Why the 'text' parameter of the breakText functions is not by default equals to "" ?

var txt = text || "";

this prevent errors like send a undefined text to this function, what you guys think?

**Comment by DavidDurman** [comment]
I don't think that should be checked. The `breakText()` function expects a string as the first argument. Actually, that is the only mandatory and most important argument. If you pass an `undefined` value instead of text, than that means that it's an error in your code. It should not be "masked" by the `breakText` function.

**Comment by josenberg** [comment]
I use this function about 23 time in my code, every time I need to do a conditional to see if the "text " is undefined, then pass the value "" to it.

Is there a better way?

**Comment by DavidDurman** [comment]
That is the good way. You should not pass arguments of a different type than expected by functions (even though JS is loosely typed). If `breakText()` should check `undefined` values, why not check if `text` is of type `function`? Or `object`? If you pass a wrong argument to a function, it should yell as soon as possible instead of trying to do some magical conversions. That would only mean it would hide errors that would go undiscovered until you're in production where it hurts much more.

`text` is simply a mandatory (not optional) argument which must be a string. Calling `breakText()` without a text does not make much sense.
