### ISSUE TITLE
Creating graph from another graph json skips port (jointjs 1.0.1)

### ISSUE THREAD

**Issue by yavneesh** [clientIO/joint#426]
Hi All,

First of all thank you for the awesome jointjs api, we have been using core version. I recently migrated to jointjs 1.0.1. I am trying to reload a graph from another graph json but it seems the newer version doesn't consider ports added using new port API methods. Could you please take a look at this https://jsfiddle.net/__ay/hyvy2mrn/5/ fiddle and let me know If I am doing anything wrong, clicking on copy will reload the graph from another graph json.  Thank you in advance, any help is much appreciated.

Thanks.
Avneesh

**Comment by kumilingus** [comment]
Hi Avneesh,

please note that an arbitrary element can have ports now (using the new Ports API) and a special view for rendering ports is no longer required (`dia.ElementView` takes care about rendering now).

In your example you are extending the `devs.Model` shape. It is a specific shape, which simplifies the current ports API by introducing `inPorts` and `outPorts` array attributes that held the ports. 
**Those are missing in your JSFiddle**. For more info please see http://resources.jointjs.com/docs/jointjs/v1.0/joint.html#shapes.devs.

In order to fix the issue you should inherit from e.g. `basic.Generic` shape instead of `devs.Model`. Please see the updated JSFiddle.
https://jsfiddle.net/fjhv8L6f/2/

**Comment by yavneesh** [comment]
Thank you.
