### ISSUE TITLE
Clusters?

### ISSUE THREAD

**Issue by filipbarak** [clientIO/joint#504]
Is there any way I could make nodes that expand/hide their children(like a cluster, but the parent node remains intact, it just expands its children) on click or any other event? Could not find it in the API or examples, or demos of joint.js, so I do apologize if I have missed it. 

Thanks for the help, awesome framework!

**Comment by kumilingus** [comment]
Here's a simple demo on how to collapse/expand children elements and links.

https://jsfiddle.net/kumilingus/o02p83mf/

The issue itself seems to be more complex. The demo does not cover:
1. nested embeds (children within children)
2. inbound/outbound links connecting a child but having the other end pinned to another "outer" element

Ad1) We would need to store the relationships between children and parents in order to reconstruct the subgraph later (The `parent` and `embeds` references are wiped out from cells when removed from the graph).

Ad2) On collapse, we can keep references to the collapsed descendants and reconnect the links to the container element. On expand, we can reconnect the links to the descendants based on the references stored.

I am not sure if creating such API would be generic enough for other use-cases though. Or whether we should leave this on the application level (supported by demos) and add some graph methods (e.g `subgraphToJSON`, `subgraphFromJSON`) to make this easier.

**Comment by kumilingus** [comment]
I am closing the issue, because there are examples available now.

- https://www.jointjs.com/demos/dwdm-circuit
- https://www.jointjs.com/demos/container
- https://www.jointjs.com/demos/activity-diagram
